title: test blog #587
author: thebatzuk
email: 
description: > # this means to ignore newlines until "baseurl:"
  Learning to use github!

# social links
twitter_username: thebatzuk
github_username: thebatzuk

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
